default: &default
  adapter: postgresql
  encoding: utf8
  pool: 2
  database: todo_app
  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: todo_app

production:
  <<: *default
  database: todo_app